#!/bin/sh
set -eux

echo "restore cloud-init to its former unbooted glory"
cloud-init clean --logs --seed

echo "remove config file disabling networking from subiquity"
rm -f /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg

echo "remove default netplan config generated by subiquity"
rm -f /etc/netplan/00-installer-config.yaml

echo "remove linux-headers"
dpkg --list \
  | awk '{ print $2 }' \
  | grep 'linux-headers' \
  | xargs apt-get -y purge;

echo "remove specific Linux kernels, such as linux-image-4.9.0-13-amd64 but keeps the current kernel and does not touch the virtual packages"
dpkg --list \
    | awk '{ print $2 }' \
    | grep 'linux-image-[234].*' \
    | grep -v `uname -r` \
    | xargs apt-get -y purge;

echo "remove linux-source package"
dpkg --list \
    | awk '{ print $2 }' \
    | grep linux-source \
    | xargs apt-get -y purge;

echo "remove all development packages"
dpkg --list \
    | awk '{ print $2 }' \
    | grep -- '-dev\(:[a-z0-9]\+\)\?$' \
    | xargs apt-get -y purge;

echo "remove droplet-agent package"
dpkg --list \
    | awk '{ print $2 }' \
    | grep droplet-agent \
    | xargs apt-get -y purge;

# echo "remove X11 libraries"
# apt-get -y purge libx11-data xauth libxmuu1 libxcb1 libx11-6 libxext6;

echo "remove obsolete networking packages"
apt-get -y purge ppp pppconfig pppoeconf;

echo "remove popularity-contest package"
apt-get -y purge popularity-contest;

echo "remove ubuntu advantage tools"
apt-get -y purge ubuntu-advantage-tools

echo "autoremoving packages and cleaning apt data"
apt-get -y autoremove;
apt-get -y clean;

echo "remove /var/cache"
find /var/cache -type f -exec rm -rf {} \;

echo "truncate any logs that have built up during the install"
find /var/log -type f -exec truncate --size=0 {} \;

echo "remove old dmesg log files"
find /var/log -type f -name 'dmesg.*' -delete

echo "blank netplan machine-id (DUID) so machines get unique ID generated on boot"
truncate -s 0 /etc/machine-id

echo "remove the contents of /tmp and /var/tmp"
rm -rf /tmp/* /var/tmp/*

echo "force a new random seed to be generated"
rm -f /var/lib/systemd/random-seed

echo "remove root ssh keys and sshd keys"
rm -f /root/.ssh/authorized_keys /etc/ssh/*key*

echo "remove everything from the ${SSH_USERNAME} user"
find "/home/${SSH_USERNAME}/" -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

echo "clear the history so our install isn't there"
rm -f /root/.wget-hsts
export HISTSIZE=0
